spring:
  profiles:
    include: oauth
  datasource:
    data: classpath:data-h2.sql
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  config:
    use-legacy-processing: true