spring:
  profiles:
    include: oauth,real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect.storage-engine: innodb
  session:
    store-type: jdbc